semi: true
printWidth: 120
singleQuote: false
trailingComma: all
arrowParens: avoid
tabWidth: 4
bracketSpacing: true
overrides:
    - files: "*.json"
      options:
          tabWidth: 2
          printWidth: 99
    - files: "*.ts"
      options:
          tabWidth: 2
          printWidth: 99
